config/routes.rb
Blog::Application.routes.draw do
  resources :blog_entries

  get "home/home"
  get "blog_entries/new"
  root :to => "blog_entries#index"

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base

	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  # GET /blog_entries
  # GET /blog_entries.xml
  def index
    @blog_entries = BlogEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blog_entries }
      format.json  { render :json => @blog_entries }
    end
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.xml
  def show
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blog_entry }
    end
  end

  # GET /blog_entries/new
  # GET /blog_entries/new.xml
  def new
    @blog_entry = BlogEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog_entry }
    end
  end

  # GET /blog_entries/1/edit
  def edit
    @blog_entry = BlogEntry.find(params[:id])
  end

  # POST /blog_entries
  # POST /blog_entries.xml
  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to(@blog_entry, :notice => 'Blog entry was successfully created.') }
        format.xml  { render :xml => @blog_entry, :status => :created, :location => @blog_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_entries/1
  # PUT /blog_entries/1.xml
  def update
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      if @blog_entry.update_attributes(params[:blog_entry])
        format.html { redirect_to(@blog_entry, :notice => 'Blog entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.xml
  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy

    respond_to do |format|
      format.html { redirect_to(blog_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  	redirect_to blog_etries
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog_entries/_form.html.erb
<%= form_for(@blog_entry) do |f| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog_entry from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :html%><br />
    <%= f.text_area :html %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_entries/edit.html.erb
<h1>Editing blog_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_entry %> |
<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/index.html.erb
<div class="container">
  
  <% @blog_entries.each do |blog_entry| %>
  <div class="blog-entry">
    <div class=" alert alert-warning"><h1><%= blog_entry.title %></h1></div>
		<pre>
	    	<%= blog_entry.html.html_safe %>
	   </pre> 
   </div>
    <hr/>
<% end %>
    
</div>

app/views/blog_entries/new.html.erb
<h1>New blog_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/show.html.erb
<div class=" alert alert-warning"> <h1> <%= @blog_entry.title %></h1></div>
<pre>
  <%= @blog_entry.html.html_safe %>
 </pre> 
<div class=" alert alert-info">  <%= @blog_entry.time %></div>

<%= link_to 'Edit', edit_blog_entry_path(@blog_entry) %> |
<%= link_to 'Back', blog_entries_path %>

app/views/home/home.html.erb
<!doctype html>
<style type="text/css">
	span{
		color: #D50909;
	}
</style>

<h1>Welcome to my blog! You are visiting at time: <span> <%= @currentTime %> </span></h1>



	<%= link_to "Blog", blog_entries_new_path %>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper fixed-navbar">
      <div class="container">
		
        <div class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <span class="navbar-brand name-title">Pawan Chopra</span>
            </div>
            <div class="navbar-collapse collapse" style="height: auto;">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#about">Projects</a></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
     <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
     
      <div id="blog-entries-carousel" class="carousel-inner">
       
       
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->

<script type="text/template" id="blog-item">
  <div class="item {{active_class}}">
          <div class="container">
            <div class="carousel-caption">
              <h1>{{title}}</h1>
              <p><a class="btn btn-large btn-primary" href="{{link}}">Read more..</a></p>
            </div>
          </div>
        </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "/bootstrap/css/bootstrap.css" %>
  <%= stylesheet_link_tag "/bootstrap/css/bootstrap-theme.css" %>
  <%= stylesheet_link_tag "/stylesheets/carousel.css" %>
  
  <%= stylesheet_link_tag "/stylesheets/highlighter/shThemeEclipse.css" %>
  <%= csrf_meta_tag %>

  <style type="text/css">


  </style>
</head>
<body>
<div>
	<%= render "layouts/header" %>
	<div class="container body-blog">
		<%= yield %>
	</div>
</div>
 <%= javascript_include_tag "/javascripts/ckeditor/ckeditor.js" %> 
  <%= javascript_include_tag "/javascripts/jquery.js" %>
  <%= javascript_include_tag "/javascripts/underscore.js" %>
  <%= javascript_include_tag "/javascripts/header.js" %>
  <%= javascript_include_tag "/bootstrap/js/bootstrap.js" %>
  <%= javascript_include_tag :defaults %>
   <%= javascript_include_tag "/javascripts/highlighter/shCore.js"%>
   <%= javascript_include_tag "/javascripts/highlighter/shBrushJScript.js"%>
   <%= javascript_include_tag "/javascripts/highlighter/shBrushJava.js"%>
   <%= javascript_include_tag "/javascripts/highlighter/shBrushXml.js"%>

</body>
</html>